### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by PrakharSrivastav** [sysco-middleware/terraform-provider-kafka#5]
Updating Kafka topics has few quirks. There are certain configurations and properties that can not be changed on the fly. `resourceKafkaTopicUpdate` function should handle these changes gracefully. 

- It should provide descriptive feedback/errors if a change in property/configuration is not supported.
- Make sure that version changes are avoided. 
- Keep the version in context before applying property/configuration changes.

**Comment by jeqo** [comment]
Solved by
